version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "saturday"
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - andrewsarnold
  labels:
  - dependencies
